In [1]:
import numpy as np
#Үнэт цаасны ТОП-10 индексийн багцыг бүрдүүлэ буй хувьцаат компаниудын санхүүгийн мэдээлэл
#Years
Years = ["2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]
Ydict = {"2012":0,"2013":1,"2014":2,"2015":3,"2016":4,"2017":5,"2018":6,"2019":7,"2020":8,"2021":9}

#Stock Companies
Companies = ["APU","AARD","GOV","ERDN","INV","TTL","TUM","ADB","MNDL","UID"]
Cdict = {"APU":0,"AARD":1,"GOV":2,"ERDN":3,"INV":4,"TTL":5,"TUM":6,"ADB":7,"MNDL":8,"UID":9}

#Income
APU_Income = [284475802102,193715871000,198468870100,0,208055307700,234606134200,512928466000,468645289700,491204352500,669724030000]
AARD_Income = [0,0,0,0,0,0,0,4371094100,5252438800,22212613200]
GOV_Income = [40826785876,48758084200,65934570400,71210860300,88673668000,0,0,0,0,0]
ERDN_Income = [0,0,0,0,0,0,0,0,0,0]
INV_Income = [0,0,0,0,0,0,10780916100,19359766400,29147505000,0]
TTL_Income = [0,161746953300,0,25322855500,176544410800,427930350000,226360600600,263521783200,254181245100,0]
TUM_Income = [0,0,0,0,0,0,17321385500,20106273900,0,0]
ADB_Income = [0,0,0,0,0,0,0,3844641400,6333651900,7768611400]
MNDL_Income = [0,0,0,0,0,0,27786499345,16422249600,17007569500,0]
UID_Income = [3000043100,3600000000,5400000000,5400000000,5400000000,5400000000,5400000000,540000000,5832000000,6706800000]
#Matrix
Income = np.array([APU_Income, AARD_Income, GOV_Income, ERDN_Income, INV_Income, TTL_Income, TUM_Income, ADB_Income, MNDL_Income, UID_Income])

#Total Profit 
APU_TP = [30980668753,4970837100,-14251672000,0,3724525900,0,0,0,0,0]
AARD_TP = [0,0,0,0,-117345700,-65496600,193151500,750324300,1662927100,1793708800]
GOV_TP = [11116964928,9295367700,13377329200,13653166400,36219080000,0,0,0,0,0]
ERDN_TP = [0,0,0,0,0,0,0,0,0,0]
INV_TP = [0,0,0,0,0,0,5056968500,9508061200,11460174000,0]
TTL_TP = [0,82176823300,0,639209900,70073490200,189378004000,68680586500,62663914000,39972023800,0]
TUM_TP = [0,0,0,0,0,0,3041163200,20106273900,0,0]
ADB_TP = [0,0,0,0,0,0,0,2369351400,2008497000,4193159800]
MNDL_TP = [0,0,0,0,0,0,3868257249,5820329600,4534068300,0]
UID_TP = [0,-804753900,103083300,149630600,-792470500,519571700,-23590400,98406500,-1896249100,436333900]
#Matrix
Profit = np.array([APU_TP, AARD_TP, GOV_TP, ERDN_TP, INV_TP, TTL_TP, TUM_TP, ADB_TP, MNDL_TP, UID_TP])

#Net Worth
APU_NW = [169776504574,267065139100,334315501100,0,291069787300,632914478600,530446697700,536709188100,556246098100,617329136000]
AARD_NW = [0,113994700,0,113994700,10900000,2712016800,3102370900,82779276900,80379860000,332610635400]
GOV_NW = [67704952566,81227070500,99978005200,122760787400,135872806000,0,0,0,0,0]
ERDN_NW = [0,0,0,0,0,0,0,0,0,0]
INV_NW = [0,0,0,0,0,0,39015181600,82322748600,135940522030,0]
TTL_NW = [0,112335058100,0,56971118000,147687060000,272838804200,157594846500,122265515100,140102360600,0]
TUM_NW = [0,0,0,0,0,0,17454709200,30695911900,0,0]
ADB_NW = [0,0,0,0,0,0,10540638561,2328078700,29656000000,77916555200]
MNDL_NW = [0,0,0,0,0,0,33784288622,40695754100,55155736500,0]
UID_NW = [0,10481337300,10401036400,9866467000,9317030000,8981606400,8597341100,8239200300,7910139600,24384394000]
#Matrix
NetWorth = np.array([APU_NW, AARD_NW, GOV_NW, ERDN_NW, INV_NW, TTL_NW, TUM_NW, ADB_NW, MNDL_NW, UID_NW])

#Debt
APU_D = [83683144852,182139163100,202230464600,0,147884315500,125988816900,86268630900,55415610500,94294376300,112536189000]
AARD_D = [0,29000,0,29000,14280000,216144100,159590200,20945455300,22721514200,69314617700]
GOV_D = [30766893289,38161274600,47434546500,54285550000,50074103000,0,0,0,0,0]
ERDN_D = [0,0,0,0,0,0,0,0,0,0]
INV_D = [0,0,0,0,0,0,25210822100,41100254400,83243728000,0]
TTL_D = [0,17446967900,0,28370405300,68678288800,105891547200,67156994000,32736845700,64027158600,0]
TUM_D = [0,0,0,0,0,0,6102679600,7776649500,0,0]
ADB_D = [0,0,0,0,0,0,6714383827,12405579300,18465645000,51168051800]
MNDL_D = [0,0,0,0,0,0,18209737894,20016761700,32501545600,0]
UID_D = [0,11420325900,11311790800,10671437000,10963919600,10149455000,9832916000,9387345100,10954533500,27281731900]
#Matrix
Debt = np.array([APU_D, AARD_D, GOV_D, ERDN_D, INV_D, TTL_D, TUM_D, ADB_D, MNDL_D, UID_D])

#Total Shares
APU_TS = [74287700,74287700,74287700,74287700,742877000,1064181553,1064181553,1064181553,1062974743,1062974743]
AARD_TS = [0,2141,0,53223,53223,1665938,1665938,28614263,28614263,28614263]
GOV_TS = [7801125,7801125,7801125,7801125,7801125,7801125,780112500,780112500, 780112500,780112500]
ERDN_TS = [0,0,0,0,0,4000000, 4000000, 4000000,267885433,0]
INV_TS = [0,0,0,0,0,0,71727918,71727918,71727918,0]
TTL_TS = [0,52665200,0,52665200,52665200,52665200,52665200,52665200,52665200,52665200]
TUM_TS = [0,0,0,0,0,0,200000000,200000000,200000000,200000000]
ADB_TS = [0,0,0,0,0,0,280000000,280000000,273560449,279753341]
MNDL_TS =[0,0,0,0,0,0,6243016,624301600,624301600,624301600]
UID_TS = [0,36807850,36807850,36807850,36807850,36807850,36807850,36807850,35121711,35124711]
#Matrix
TotalShares = np.array([APU_TS, AARD_TS, GOV_TS, ERDN_TS, INV_TS, TTL_TS, TUM_TS, ADB_TS, MNDL_TS, UID_TS])

#Value per Share
APU_VPS = [1159,1143,1778,0,193,475,416,451,429,475]
AARD_VPS = [0,2141,0,2141,-64,1498,1766,2161,2015,9202]
GOV_VPS = [4735,5520,6735,8778,10998,0,0,0,0,0]
ERDN_VPS = [0,0,0,0,0,0,0,0,0,0]
INV_VPS = [0,0,0,0,0,0,194,575,735,0]
TTL_VPS = [0,1802,0,543,1500,3170,1717,1700,1445,0]
TUM_VPS = [0,0,0,0,0,0,57,115,0,0]
ADB_VPS = [0,0,0,0,0,0,13,39,41,96]
MNDL_VPS = [0,0,0,0,0,0,2495,33,36,0]
UID_VPS = [0,-26,-25,-22,-45,-32,-34,-31,-87,-82]
#Matrix
ValueperShare = np.array([APU_VPS, AARD_VPS, GOV_VPS, ERDN_VPS, INV_VPS, TTL_VPS, TUM_VPS, ADB_VPS, MNDL_VPS, UID_VPS])             

In [3]:
Debt

array([[ 83683144852, 182139163100, 202230464600,            0,
        147884315500, 125988816900,  86268630900,  55415610500,
         94294376300, 112536189000],
       [           0,        29000,            0,        29000,
            14280000,    216144100,    159590200,  20945455300,
         22721514200,  69314617700],
       [ 30766893289,  38161274600,  47434546500,  54285550000,
         50074103000,            0,            0,            0,
                   0,            0],
       [           0,            0,            0,            0,
                   0,            0,            0,            0,
                   0,            0],
       [           0,            0,            0,            0,
                   0,            0,  25210822100,  41100254400,
         83243728000,            0],
       [           0,  17446967900,            0,  28370405300,
         68678288800, 105891547200,  67156994000,  32736845700,
         64027158600,            0],
       [  

In [4]:
Debt[2]

array([30766893289, 38161274600, 47434546500, 54285550000, 50074103000,
                 0,           0,           0,           0,           0],
      dtype=int64)

In [5]:
Debt[2,4]

50074103000

In [6]:
Debt[2][4]

50074103000

In [7]:
Debt[Cdict["GOV"],Ydict["2016"]]

50074103000

In [8]:
#Нийт хөрөнгийн эргэц
import warnings as w
w.filterwarnings('ignore')
a1 = np.matrix.round(Income / NetWorth*100)
a1

array([[168.,  73.,  59.,  nan,  71.,  37.,  97.,  87.,  88., 108.],
       [ nan,   0.,  nan,   0.,   0.,   0.,   0.,   5.,   7.,   7.],
       [ 60.,  60.,  66.,  58.,  65.,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  28.,  24.,  21.,  nan],
       [ nan, 144.,  nan,  44., 120., 157., 144., 216., 181.,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  99.,  66.,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,   0., 165.,  21.,  10.],
       [ nan,  nan,  nan,  nan,  nan,  nan,  82.,  40.,  31.,  nan],
       [ inf,  34.,  52.,  55.,  58.,  60.,  63.,   7.,  74.,  28.]])

In [9]:
#Өрийн харьцаа
import warnings as w
w.filterwarnings('ignore')
a1 = np.matrix.round(Debt / NetWorth*100)
a1

array([[ 49.,  68.,  60.,  nan,  51.,  20.,  16.,  10.,  17.,  18.],
       [ nan,   0.,  nan,   0., 131.,   8.,   5.,  25.,  28.,  21.],
       [ 45.,  47.,  47.,  44.,  37.,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  65.,  50.,  61.,  nan],
       [ nan,  16.,  nan,  50.,  47.,  39.,  43.,  27.,  46.,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  35.,  25.,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  64., 533.,  62.,  66.],
       [ nan,  nan,  nan,  nan,  nan,  nan,  54.,  49.,  59.,  nan],
       [ nan, 109., 109., 108., 118., 113., 114., 114., 138., 112.]])

In [ ]:
#ашгийн өсөлт бууралт
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(Profit[1], c = 'Black', ls ='--', marker='s', ms = 5)
plt.xticks(list(range(0,10)), Years, rotation = 'vertical')
plt.show()